config/routes.rb
Rails.application.routes.draw do

  resources :pizzas
  resources :pizzas
  devise_for :users
  resources :articles

  get 'welcome/index'

  get 'abouts/index'

  get 'pizza/' => 'pizza#index'

  get 'bestof/' => 'bestof#index'

  get 'abouts/' => 'abouts#index'

  get 'articles/' => 'articles#index'

  get 'admins/' => 'admins#index'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
end

app/models/pizza.rb
class Pizza < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles       

  # Setup accessible (or protected) attributes for your model
	# attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
	def index
	end

	# def new
	# end

	def show
	end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
		@articles = Article.all
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  # before_action :authenticate_user!

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    new_article_path
  end

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
  		devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
  	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_filter :check_access, :only => [:new, :create, :edit, :destroy]

	def index
		@articles = Article.all
	end

	# def index
	# 	@article = Article.paginate(page: params[:page], :per_page => 5)
	# end

	def show
		@article = Article.find(params[:id])
	end


	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		@article.save
		redirect_to @article
	end

	def update
		@article = Article.find(params[:id])

		@article.update(article_params)
		redirect_to @article
	end

	def edit
		@article = Article.find(params[:id])
	end

	def destroy
		Article.find(params[:id]).destroy
		flash[:success] = "Review deleted"
		redirect_to admins_path
	end

	protected
  def check_access
    redirect_to '/' and return unless current_user
  end

	private
		def article_params
			params.require(:article).permit(:author, :date, :headline, :text, :image_link)
		end
end

app/controllers/bestof_controller.rb
class BestofController < ApplicationController
	def index
		@pizzas = Pizza.all
    @hash = Gmaps4rails.build_markers(@pizzas) do |pizza, marker|
      marker.lat pizza.latitude
      marker.lng pizza.longitude
      marker.title pizza.title
    end
	end

	def show
	end
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
    @hash = Gmaps4rails.build_markers(@pizzas) do |pizza, marker|
      marker.lat pizza.latitude
      marker.lng pizza.longitude
      marker.title pizza.title
    end
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@articles = Article.all

  	@pizzas = Pizza.all
    @hash = Gmaps4rails.build_markers(@pizzas) do |pizza, marker|
      marker.lat pizza.latitude
      marker.lng pizza.longitude
      marker.title pizza.title
    end
  end

  def show
		@article = Article.find(params[:id])
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bestof_helper.rb
module BestofHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/helpers/top_tens_helper.rb
module TopTensHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/abouts/index.html.erb
<div class="container-fluid">
	<div class="about row">
		<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-9 col-sm-offset-1 col-xs-9 col-xs-offset-1 rev_index_head">
			<h3>ABOUT</h3>
			<div>Three Person Pizza Club was founded in 2012 by three friends who love pizza. We eat pizza all around Austin in search of the best pie. We consider the crust, the sauce, the cheese, the toppings, and the atmosphere of the pizzaria. We would eat pizza for breakfast, lunch, and dinner. Wait, sometimes we do. Pizza forever!
			</div>
		</div>	
	</div>

	<div class="row">
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 ppl">
			<div>
				<img src="http://lorempizza.com/250/250" class="ppl_pics img-responsive">
			</div>
			<div>
				<div class="ppl_name">Caitlyn Collins</div>
				<div class="ppl_text">Caitlyn loves pizza. It is her favorite food of all time.
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 ppl">
			<div>
				<img src="http://lorempizza.com/250/250" class="ppl_pics">
			</div>
			<div>
				<div class="ppl_name">Lauren Grant</div>
				<div class="ppl_text">Lauren loves pizza. It is her favorite food of all time.
				</div>
			</div>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 ppl">
			<div>
				<img src="http://lorempizza.com/250/250" class="ppl_pics">
			</div>	
			<div>
				<div class="ppl_name">Amanda Moon</div>
				<div class="ppl_text">Amanda loves pizza. It is her favorite food of all time.
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admins/index.html.erb
<% if user_signed_in? %>

	<div class="main">
		<%= button_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-primary', :method => :get %> 
  	<%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-large btn-danger' %>
	  <h2>Welcome back, pizza friend!</h2>
	  <p class="lead">Post, edit, or delete reviews here.</p>

	  <div class="row-fluid">
			<div class="span6">
				<a href="/articles/new">POST NEW REVIEW</a>
			</div>
		</div>

		<% @articles.each do |article| %>

		<div class="row">
			<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3 rev_index_head">
				<h3><%= article.headline %></h3>
				<div><%= article.date.to_s(:long) %></div>
				<div><%= article.author %></div>
			</div>
		</div>

		<div class="row-fluid">
			<div class="span6">
				<a href="/articles/<%= article.id %>/edit">EDIT</a>
			</div>	
			<div class="span6">
		  	<%= link_to "DELETE", article_path(article), :method => :delete, data: { confirm: "Are you sure you want to delete this review?" } %>
		  </div>	
		</div>
		
			<% end %>

<% else %>
	<div class="main">
		<h2>Welcome, new pizza friend!</h2>
		<p class="lead">Sign in to edit this awesome pizza site.</p>
		<div class="row-fluid">
			<div class="span6">
			  <%= button_to "Login", new_user_session_path, :class => 'btn btn-primary', :method => :get   %>
	  	</div>
	  </div>
	</div>  
<% end %>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/articles/edit.html.erb
<p class="navbar-text pull-right">
	<% if user_signed_in? %>
		<%= link_to 'EDIT MAP', pizzas_path, :class => 'navbar-link' %> |
		<%= link_to 'EDIT ARTICLES', admins_path, :class => 'navbar-link' %> |
	  <%= link_to 'EDIT PROFILE', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
	<% else %>

	  <%= link_to "LOGIN", new_user_session_path, :class => 'navbar-link' %>
	 
	<% end %>
</p>

<h2 class="rev_form_head">Edit your review</h2>
<div class="rev_form">
	<%= form_for @article do |f| %>
		<p>
			<%= f.label :author %><br>
			<%= f.text_field :author, class: 'form-control' %>
		</p>

		<p>
			<%= f.label :date %><br>
			<%= f.date_field :date, class: 'form-control'%>
		</p>

		<p>
			<%= f.label :headline %><br>
			<%= f.text_field :headline, class: 'form-control' %>
		</p>

		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text, class: 'form-control' %>
		</p>

		<p>
			<%= f.label :image_link %><br>
			<%= f.text_area :image_link, class: 'form-control' %>
		</p>

		<p>
			<%= f.submit "Save changes" %>
		</p>
	<% end %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>

<div class="row-fluid">
	<div class="rev_image ">
		<img class="img-responsive" src="<%= article.image_link %>" width="400" height="150">
	</div>
</div>

<div class="row">
	<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3 rev_index_head">
		<h3><%= article.headline %></h3>
		<div><%= article.date.to_s(:long) %></div>
		<div><%= article.author %></div>
	</div>
</div>

<div class="row">
	<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2 rev_index_text">
		<div><p><%= article.text %></p>
	</div>
</div>

<div class="row">
	<div class="col-lg-4 col-lg-offset-4 col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4 col-xs-8 col-xs-offset-2 ratings">
		<div>
			CRUST:<br>
			SAUCE:<br>
			CHEESE:<br>
			TOPPINGS:<br>
			ORIGINALITY:<br>
			ATMOSPHERE:<br>
		</div>
	</div>
</div>

<% end %>

app/views/articles/new.html.erb
<p class="navbar-text pull-right">
	<% if user_signed_in? %>
		<%= link_to 'EDIT MAP', pizzas_path, :class => 'navbar-link' %> |
		<%= link_to 'EDIT ARTICLES', admins_path, :class => 'navbar-link' %> |
	  <%= link_to 'EDIT PROFILE', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> 
	<% else %>

	  <%= link_to "LOGIN", new_user_session_path, :class => 'navbar-link' %>
	 
	<% end %>
</p>

<h2 class="rev_form_head">Post a new review here</h2>
<div class="rev_form">
	<%= form_for :article, url: articles_path do |f| %>
		<p>
			<%= f.label :author %><br>
			<%= f.text_field :author %>
		</p>

		<p>
			<%= f.label :date %><br>
			<%= f.date_field :date %>
		</p>

		<p>
			<%= f.label :headline %><br>
			<%= f.text_field :headline %>
		</p>

		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text %>
		</p>

		<p>
			<%= f.label :image_link %><br>
			<%= f.text_area :image_link %>
			<div>PLEASE NOTE: IMAGE MUST BE<br>
				380 X 300 PIXELS (WIDTH X HEIGHT)<DIV>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/articles/show.html.erb
<p class="navbar-text pull-right">
	<% if user_signed_in? %>
		<%= link_to 'EDIT MAP', pizzas_path, :class => 'navbar-link' %> |
		<%= link_to 'EDIT ARTICLES', admins_path, :class => 'navbar-link' %> |
	  <%= link_to 'EDIT PROFILE', edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
</p>

<h2 class="rev_form_head">This review has been posted.</h2>

<div class="article_text">
	<div class="row-fluid">
		<div class="span6">
			<%= @article.author %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= @article.date.to_s(:long) %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<strong><%= @article.headline %></strong>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= @article.text %>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span6">
			<%= @article.image_link %>
		</div>
	</div>	

	<div class="row-fluid">
		<div class="span6">
			<%= button_to 'Post another review', new_article_path, :method => :get %>
		</div>
	</div>	

	<div class="row-fluid">
		<div class="span6">
			<%= button_to "Edit review", edit_article_path, :method => :get %>
		</div>
	</div>	

	<div class="row-fluid">
		<div class="span6">
		  <%= button_to "Delete", article_path(@article), :method => :delete, data: { confirm: "Are you sure you want to delete this review?" } %>
		</div>
	</div>
</div>	

<% else %>

	<div class="row-fluid">
		<div class="rev_image">
			<img class="img-responsive" src="<%= @article.image_link %>" width="400" height="150">
		</div>
	</div>

  <div class="row">
		<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3 rev_index_head">
			<h3><%= @article.headline %></h3>
			<div><%= @article.date.to_s(:long) %></div>	
			<div><%= @article.author %></div>
		</div>
	</div>

	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2 rev_index_text">
			<div><%= @article.text %></div>
		</div>
	</div>
 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>3PPC</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://necolas.github.io/normalize.css/3.0.2/normalize.css" />
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>
	<header class="font">
  		<nav class="navbar navbar-default">
  			<div class="container-fluid nav-links">
			    <!-- Brand and toggle get grouped for better mobile display -->
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand hover" href="/"><img src="http://i.imgur.com/uohDwhf.png" style="height: 100%"></a>
			    </div>
			    <!-- Collect the nav links, forms, and other content for toggling -->
			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			      <ul id="nav-links"class="nav navbar-nav">
			        <li><a class="hover"><%= link_to "REVIEWS", articles_path %></a></li>
			    		<li><a class="hover"><%= link_to "THE BEST LIST", bestof_path %></a></li>
			    		<li><a class="hover"><%= link_to "ABOUT", abouts_path %></a></li>
			      </ul>
			      <form class="navbar-form navbar-right" role="search">
        			<div class="form-group">
          			<input type="text" class="form-control" placeholder="Search">
        			</div>
        			<button type="submit" class="btn btn-default">
        				<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        			</button>
      			</form>
			      <!-- <ul class="nav navbar-nav navbar-right">
			        <li><a class="hover" href="#">JOKES</a></li>
			      </ul> -->
    			</div><!-- /.navbar-collapse -->
  			</div><!-- /.container-fluid -->
			</nav>
  	</header>

<%= yield %>

</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(@pizza) do |f| %>
  <% if @pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% @pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/index.html.erb
<% if user_signed_in? %>

  <script src="//maps.google.com/maps/api/js?v=3.23&libraries=geometry" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

  <p id="notice"><%= notice %></p>
  <h1>Listing Pizzas</h1>
  <table>
    <thead>
      <tr>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Address</th>
        <th>Description</th>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pizzas.each do |pizza| %>
        <tr>
          <td><%= pizza.latitude %></td>
          <td><%= pizza.longitude %></td>
          <td><%= pizza.address %></td>
          <td><%= pizza.description %></td>
          <td><%= pizza.title %></td>
          <td><%= link_to 'Show', pizza %></td>
          <td><%= link_to 'Edit', edit_pizza_path(pizza) %></td>
          <td><%= link_to 'Destroy', pizza, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Pizza', new_pizza_path %>

  <div style='width: 300px;'>
    <div id="map" style='width: 300px; height: 300px;'></div>
  </div>
  <script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
  </script>

<% else %>
  <div class="main">
    <h2>Welcome, new pizza friend!</h2>
    <p class="lead">Sign in to edit this awesome pizza site.</p>
    <div class="row-fluid">
      <div class="span6">
        <%= button_to "Sign up", new_user_registration_path, :class => 'btn btn-primary', :method => :get   %> 
      </div>
      <div class="span6">
        <%= button_to "Login", new_user_session_path, :class => 'btn btn-primary', :method => :get   %>
      </div>
    </div>
  </div>  
<% end %>  

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @pizza.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @pizza.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @pizza.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pizza.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pizza.title %>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>

app/views/welcome/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.23&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<div class="jumbotron">
		<div class="row">
		  <div class="current col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
		  	<h3>Welcome to the 3 Person Pizza Club!</h3>
		  	<img src="http://i.imgur.com/uohDwhf.png">
		  	<!-- <p><a class="btn btn-default btn-md" href="#" role="button">READ THE REVIEW</a></p> -->
		  </div>
	  </div> 
</div>

<div class="container-fluid">
	<div class="row">
		<div class="col-lg-9 col-md-9 col-sm-9 col-xs-9"

			<% @articles.each do |article| %>

				<!-- REVIEW IMAGE -->
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 rev_img">
					<img class="img-responsive" src="<%= article.image_link %>" width="380" height="300">
				</div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 rev_text">
					<h3><%= article.headline %></h3>
					<div><%= truncate article.text, length: 510, separator: ' ' %>
						<%= link_to 'READ MORE', article_path(article) %>
					</div>
				</div>
			<% end %>	
		</div>
	
		<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12 ">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 top_ten" style='width: 300px; height: 260px;'>
					<h3>THE BEST LIST</h3>
					<ul>
						<li><%= link_to 'Backspace', 'http://thebackspace-austin.com/' %></li>
						<li><%= link_to 'Bufalina', 'http://www.bufalinapizza.com/' %></li>
						<li><%= link_to 'Via 313', 'http://www.via313.com/' %></li>
						<li><%= link_to 'Burn', 'http://burnatx.com/' %></li>
						<li><%= link_to 'East Side Pies', 'http://eastsidepies.com/' %></li>
						<li><%= link_to 'Little Deli', 'http://www.littledeliandpizza.com/' %></li>
						<li><%= link_to 'House Pizzeria', 'http://www.housepizzeria.com/' %></li>
						<li><%= link_to 'Unit-D Pizzeria', 'http://www.housepizzeria.com/' %></li>
						<li><%= link_to 'Home Slice Pizza', 'https://www.homeslicepizza.com/' %></li>
						<li><%= link_to 'Vespaio', 'http://austinvespaio.com/' %></li>
					</ul>
				</div>

				<div id="map_text">
					<%= link_to "PIZZA MAP", bestof_path %>
				</div>
				<div style='width: 300px;' class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
  				<div id="map" style='width: 300px; height: 300px;'></div>
				</div>
				<script type="text/javascript">
				  handler = Gmaps.build('Google');
				  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
				    markers = handler.addMarkers(<%=raw @hash.to_json %>);
				    handler.bounds.extendWith(markers);
				    handler.fitMapToBounds();
				  });
				</script>
			</div>		
		</div>
	</div>
</div>		
		
		
	
	